### ISSUE TITLE
Missing write option variable_names/1

### ISSUE THREAD

**Issue by UWN** [ichiban/prolog#188]
[README.md](https://github.com/ichiban/prolog/blob/main/README.md) misses the write option [`variable_names/1`](http://www.complang.tuwien.ac.at/ulrich/iso-prolog/variable_names) (since Cor.3).

**Comment by ichiban** [comment]
@UWN Thank you very much for pointing out! I implemented `variable_names/1` as a write option and released `v0.9.1`.

You can check it via `1pl`, the top level command for testing.

```console
$ go install github.com/ichiban/prolog/cmd/1pl@latest
go: downloading github.com/ichiban/prolog v0.9.1
$ $(go env GOPATH)/bin/1pl
Top level for ichiban/prolog v0.9.1
This is for testing purposes only!
See https://github.com/ichiban/prolog for more details.
Type Ctrl-C or 'halt.' to exit.
?- write_term('F'(X, Y), [quoted(true), variable_names(['Foo'=X, 'Bar'=X, 'Baz'=Y])]), nl.
'F'(Foo, Baz)
X = _1009,
Y = _1023.
```

**Comment by UWN** [comment]
Please note that there are many specific errors in specific situations. See the [error classes](http://www.complang.tuwien.ac.at/ulrich/iso-prolog/error_k#error_classes) for an overview. I just started with query [#1](http://www.complang.tuwien.ac.at/ulrich/iso-prolog/variable_names#1).

```
?- write_term(T,[quoted(true),
|-  variable_names([N=T])]). 
2022/04/08 21:22:17 error(domain_error(write_option, variable_names(_1033)), 'Invalid value for write_option.') % unexpected
```
Expected: instantiation_error.

As for the second argument of error/2 you can certainly put there what you believe is best. But many just indicate the predicate as such. "Invalid value" is pretty ambiguous in Prolog terminology. In particular, because a variable is not really considered to be a value.

**Comment by UWN** [comment]
Reopened, because [#1](http://www.complang.tuwien.ac.at/ulrich/iso-prolog/variable_names#1) is still not solved.

**Comment by UWN** [comment]
Reopened, because [#1](http://www.complang.tuwien.ac.at/ulrich/iso-prolog/variable_names#1) is still not solved.

**Comment by ichiban** [comment]
@UWN Thank you very much for pointing this out! I fixed `write_term/3` so that it raises respective exceptions for invalid variable_names. Also, the second argument of `error/2` is now the predicate indicator.

```console
$ git checkout main
Already on 'main'
Your branch is up to date with 'origin/main'.
$ go install github.com/ichiban/prolog/cmd/1pl
$ $(go env GOPATH)/bin/1pl
Top level for ichiban/prolog (devel)
This is for testing purposes only!
See https://github.com/ichiban/prolog for more details.
Type Ctrl-C or 'halt.' to exit.
?- write_term(T,[quoted(true),
|-  variable_names([N=T])]).
2022/06/17 09:56:10 error(instantiation_error, write_term/3)
?- 
```

**Comment by UWN** [comment]
Very good. Now there is [#11](http://www.complang.tuwien.ac.at/ulrich/iso-prolog/variable_names#11) and 12.

The test cases are also available as Questions Using Answer Descriptions ([quad](http://www.complang.tuwien.ac.at/ulrich/iso-prolog/variable_names_quad.pl)).

(And, as far as I understand, your `length/2` updates are not present in the main branch, right?)

**Comment by UWN** [comment]
Note that case 11 is highlighted as a "regular use" case. So it is very likely that this case occurs also in error free programs.

**Comment by ichiban** [comment]
`length/2` is not yet in the main branch since it conflicts with the recent parser/lexer overhaul. I'll merge it into the main branch next.

**Comment by ichiban** [comment]
@UWN I went through all the cases in http://www.complang.tuwien.ac.at/ulrich/iso-prolog/variable_names. The latest release passes them.

```console
$ go install github.com/ichiban/prolog/cmd/1pl@latest
go: downloading github.com/ichiban/prolog v0.10.0
$ $(go env GOPATH)/bin/1pl
Top level for ichiban/prolog v0.10.0
This is for testing purposes only!
See https://github.com/ichiban/prolog for more details.
Type Ctrl-C or 'halt.' to exit.
?- T = a, N = 'Any', /**/write_term(T,[quoted(true),variable_names([N=T])]).
aT = a,
N = 'Any'.
?- T = '$VAR'(9), N = '_', /**/write_term(T,[quoted(true),variable_names([N=T])]
).
'$VAR'(9)T = '$VAR'(9),
N = '_'.
```

**Comment by UWN** [comment]
[#13](http://www.complang.tuwien.ac.at/ulrich/iso-prolog/variable_names#13) is incorrect. The variable name *has* to start with an underscore. The remaining letters are implementation dependent. But you cannot just write out a variable name without that underscore.

```
?- write_term(T,[quoted(true),variable_names(['X'=X,'Y'=Y,'Z'=Z])]).
TT = T,
X = _2121,
Y = _2135,
Z = _2149.
?- write_term(T,[quoted(true),variable_names(['X'=X,'Y'=Y,'Z'=Z])]), false.
Tfalse.
?- write_term(Txc,[quoted(true),variable_names(['X'=X,'Y'=Y,'Z'=Z])]), false.
Txcfalse.
```

**Comment by ichiban** [comment]
As of newly released `v0.10.3`, `write_term/3` binds non-anonymous variables with fresh anonymous variables.

```console
$ go install github.com/ichiban/prolog/cmd/1pl@latest
go: downloading github.com/ichiban/prolog v0.10.3
$ $(go env GOPATH)/bin/1pl
Top level for ichiban/prolog v0.10.3
This is for testing purposes only!
See https://github.com/ichiban/prolog for more details.
Type Ctrl-C or 'halt.' to exit.
?- write_term(T,[quoted(true),variable_names(['X'=X,'Y'=Y,'Z'=Z])]).
_1159T = _1162,
X = _1100,
Y = _1114,
Z = _1128;
?- write_term(T,[quoted(true),variable_names(['X'=X,'Y'=Y,'Z'=Z])]), false.
_1261false.
?- write_term(Txc,[quoted(true),variable_names(['X'=X,'Y'=Y,'Z'=Z])]), false.
_1367false.
```

**Comment by UWN** [comment]
[#51](http://www.complang.tuwien.ac.at/ulrich/iso-prolog/variable_names#51):

```
?- VN_list = [T='T'|non_list], /**/write_term(T,[variable_names(VN_list)]).
2022/08/01 19:37:34 error(instantiation_error,write_term/3), unexpected
```

**Comment by UWN** [comment]
> `write_term/3` binds non-anonymous variables with fresh anonymous variables.

There would be nothing wrong to include the original name somehow. However, it is important that the actual printed name starts with `_` and (certainly) that it is unique, at least within a single `write_term/3`.

**Comment by ichiban** [comment]
https://github.com/ichiban/prolog/issues/188#issuecomment-1201511476

I think you're referring to [#35](https://www.complang.tuwien.ac.at/ulrich/iso-prolog/variable_names#35) which accepts `instantiation_error` while [#51](http://www.complang.tuwien.ac.at/ulrich/iso-prolog/variable_names#51) accepts `domain_error(write_option,variable_names([=(T,_)|non_list]))`

```console
$ $(go env GOPATH)/bin/1pl
Top level for ichiban/prolog v0.10.3
This is for testing purposes only!
See https://github.com/ichiban/prolog for more details.
Type Ctrl-C or 'halt.' to exit.
?- VN_list = [T='T'|non_list], write_term(T, [variable_names(VN_list)]). % #35
2022/08/02 08:59:20 error(instantiation_error,write_term/3)
?- VN_list = ['T'=T|non_list], write_term(T, [variable_names(VN_list)]). % #51
2022/08/02 08:59:33 error(domain_error(write_option,variable_names([=(T,_1164)|non_list])),write_term/3)
?- 
```

**Comment by UWN** [comment]
You are right, I was wrong. Please check [your new entry](https://www.complang.tuwien.ac.at/ulrich/iso-prolog/variable_names)!
